### ISSUE TITLE
After updating to 1.2.1 the "End Keg" button fails

### ISSUE THREAD

**Issue by jgustie** [Kegbot/kegbot-server#326]
I can't seem to end a keg running 1.2.1, I get a 500 error. [Debug traceback](http://dpaste.com/3KZ015X).

```
AttributeError at /kegadmin/taps/5/
'KegTap' object has no attribute 'status'
Request Method:	POST
Request URL:	.../kegadmin/taps/5/
Exception Type:	AttributeError
Exception Value:	'KegTap' object has no attribute 'status'
Exception Location:	/data/kb/local/lib/python2.7/site-packages/pykeg/backend/backends.py in end_keg, line 511
```
